### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by netpoetica** [adunkman/node-trello#9]
I'm running a .get function to get the boards of my organization - when I run it via  the browser, I get back an array, but when I run it over my express app I get this string "model not found" (if i console.log the object). I'm curious if you guys have any insight into this?

I also ran the node-trello app locally and the local version was able to complete this request sucesffully, giving me back an array of boards. Again, this only seems to happen when I run it inside of an express app.get() or app.post() function as a callback.

I couldn't find any info on this particular error from the Trello API website, so I am curious if maybe this is something that node-trello comes up with or if anyone else has encountered this?

**Comment by singhshashi** [comment]
In my particular case, I was getting the error because an async operation which saves the userDetails from trello was not finished and this led to the request going to Trello api to be bad some of the times. as the api request was using userDetails to build the url for the api call. i.e. 

```
 console.log('userDetailsInTrelloSettings:%O', TrelloSettings.userDetails);
    return new Promise(function (fulfill, reject) {
      trello.get('1/members/' + TrelloSettings.userDetails.username + '/boards?filter=open', function (err, data) {
        if (err) reject(err);
        fulfill(data);
      });
    });
```

TrelloSettings.userDetails was an empty object when the error was thrown. No error was thrown on subsequent runs.

**Comment by awaistechverx** [comment]
How did you fix this? i am facing this issue now, after little long
